import { resolveStudioAssetPublicSrc } from '@/data/assets'
import {
  SIGNATURE_CERTIFICATION_LOGO_VALUES,
  SIGNATURE_EXPERIENCE_LOGO_VALUES,
  getSignatureEducationLogoValues,
  normalizeSignatureLogos,
} from '@/lib/signature-logo-groups'
import { formatSignatureAffiliation, getSignatureAffiliationDisplayRows } from '@/lib/signature-identity'
import type { EmailSignatureTemplate, LogoAsset } from '@/types'

const STUDIO_ASSET_ORIGIN = (import.meta.env.VITE_SIGNATURE_ASSET_ORIGIN || 'https://tylerbustard.com').replace(/\/+$/u, '')

// Maps a contact item key to its hosted PNG icon (generated by scripts/gen-icons.mjs).
const SIGNATURE_CONTACT_ICON_FILES: Record<string, string> = {
  phone: 'phone',
  email: 'mail',
  website: 'globe',
  location: 'map-pin',
}

type SignatureHtmlContactItem = {
  key: string
  value: string
  href: string
}

type SignatureHtmlLogo = {
  alt: string
  src: string
}

const escapeHtml = (value: string) =>
  value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')

const toAbsoluteStudioAssetUrl = (
  src: string,
  logoTone: EmailSignatureTemplate['data']['logoTone'] = 'original',
) => {
  const resolved = resolveStudioAssetPublicSrc(src, src, logoTone)
  if (!resolved) return ''
  if (resolved.startsWith('http://') || resolved.startsWith('https://') || resolved.startsWith('data:')) {
    return resolved
  }

  return new URL(resolved, STUDIO_ASSET_ORIGIN).toString()
}

const getSignatureContactItems = (template: EmailSignatureTemplate): SignatureHtmlContactItem[] => {
  const { data } = template

  return [
    data.phone
      ? {
          key: 'phone',
          value: data.phone,
          href: `tel:${data.phone.replace(/[^+\d]/gu, '')}`,
        }
      : null,
    data.email
      ? {
          key: 'email',
          value: data.email,
          href: `mailto:${data.email}`,
        }
      : null,
    data.website
      ? {
          key: 'website',
          value: data.website,
          href: `https://${data.website.replace(/^https?:\/\//u, '')}`,
        }
      : null,
    data.location
      ? {
          key: 'location',
          value: data.location,
          href: '',
        }
      : null,
  ].filter((item): item is SignatureHtmlContactItem => Boolean(item))
}

const normalizeLogoGroup = (logos: LogoAsset[] = [], logoTone: EmailSignatureTemplate['data']['logoTone']) =>
  logos.map((logo) => ({
    alt: logo.alt,
    src: toAbsoluteStudioAssetUrl(logo.src, logoTone),
  }))

const renderLogoCellsHtml = (logos: SignatureHtmlLogo[]) =>
  logos
    .map((logo, index) => {
      const rightPadding = index === logos.length - 1 ? '0' : '10px'

      return `
        <td style="padding:0 ${rightPadding} 0 0;vertical-align:middle;">
          <img
            src="${escapeHtml(logo.src)}"
            alt="${escapeHtml(logo.alt)}"
            style="display:block;height:13px;width:auto;max-width:60px;opacity:0.66;border:0;outline:none;text-decoration:none;image-rendering:-webkit-optimize-contrast;"
          />
        </td>
      `
    })
    .join('')

const renderLogoRailHtml = (...logoGroups: SignatureHtmlLogo[][]) => {
  const visibleGroups = logoGroups.filter((logos) => logos.length > 0)
  if (visibleGroups.length === 0) return ''

  const groupCells = visibleGroups
    .map((logos, index) => {
      const rightPadding = index === visibleGroups.length - 1 ? '0' : '13px'

      return `
        <td style="padding:0 ${rightPadding} 0 0;vertical-align:middle;">
          <table cellpadding="0" cellspacing="0" border="0" role="presentation" style="border-collapse:collapse;">
            <tr>${renderLogoCellsHtml(logos)}</tr>
          </table>
        </td>
      `
    })
    .join('')

  return `
    <table cellpadding="0" cellspacing="0" border="0" role="presentation" style="border-collapse:collapse;">
      <tr>${groupCells}</tr>
    </table>
  `
}

export const buildSignaturePlainText = (template: EmailSignatureTemplate) => {
  const { data } = template
  const affiliation = formatSignatureAffiliation(data)
  const lines = [
    data.signoff || 'Best regards,',
    '',
    data.name,
    affiliation,
    ...getSignatureContactItems(template).map((item) => item.value),
  ].filter((line) => line.trim().length > 0)

  return lines.join('\n')
}

export const buildSignatureHtmlFragment = (template: EmailSignatureTemplate) => {
  const { data } = template
  const affiliationRows = getSignatureAffiliationDisplayRows(data)
  const hasAffiliation = affiliationRows.length > 0

  const profileSrc = toAbsoluteStudioAssetUrl(data.profileSrc)
  const experienceLogos = normalizeLogoGroup(
    normalizeSignatureLogos(data.experienceLogos, SIGNATURE_EXPERIENCE_LOGO_VALUES),
    data.logoTone,
  )
  const educationLogos = normalizeLogoGroup(
    normalizeSignatureLogos(data.educationLogos, getSignatureEducationLogoValues(template.id)),
    data.logoTone,
  )
  const certificationLogos = normalizeLogoGroup(
    normalizeSignatureLogos(data.certificationLogos, SIGNATURE_CERTIFICATION_LOGO_VALUES),
    data.logoTone,
  )

  const contactItems = getSignatureContactItems(template)

  const contactRailHtml = contactItems
    .map((item, index) => {
      const separatorHtml =
        index < contactItems.length - 1
          ? `<td style="padding:0 11px 0 0;vertical-align:middle;color:#cbd5e1;font-family:'Aptos','Segoe UI','Helvetica Neue',Arial,sans-serif;font-size:12.5px;line-height:1.35;">|</td>`
          : ''
      const valueHtml = item.href
        ? `<a href="${escapeHtml(item.href)}" style="color:#64748b;text-decoration:none;">${escapeHtml(item.value)}</a>`
        : escapeHtml(item.value)

      // Icon + text are nested in a tiny table for reliable vertical alignment across
      // mail clients (inline SVG/flex are unreliable; a hosted PNG in a cell is robust).
      const iconFile = SIGNATURE_CONTACT_ICON_FILES[item.key]
      const iconHtml = iconFile
        ? `<td style="padding:0 5px 0 0;vertical-align:middle;line-height:0;font-size:0;"><img src="${escapeHtml(`${STUDIO_ASSET_ORIGIN}/ai-assets/icons/${iconFile}.png`)}" width="13" height="13" alt="" style="display:block;width:13px;height:13px;border:0;outline:none;text-decoration:none;" /></td>`
        : ''

      return `
        <td style="padding:0 11px 0 0;vertical-align:middle;">
          <table cellpadding="0" cellspacing="0" border="0" role="presentation" style="border-collapse:collapse;">
            <tr>
              ${iconHtml}
              <td style="vertical-align:middle;color:#64748b;font-family:'Aptos','Segoe UI','Helvetica Neue',Arial,sans-serif;font-size:12.5px;line-height:1.35;white-space:nowrap;">${valueHtml}</td>
            </tr>
          </table>
        </td>
        ${separatorHtml}
      `
    })
    .join('')

  const logoRailHtml = renderLogoRailHtml(experienceLogos, educationLogos, certificationLogos)

  return `
    <table cellpadding="0" cellspacing="0" border="0" role="presentation" style="border-collapse:collapse;background:#ffffff;font-family:'Aptos','Segoe UI','Helvetica Neue',Arial,sans-serif;color:#0f172a;max-width:620px;">
      <tr>
        <td style="padding:0;background:#ffffff;">
          <table cellpadding="0" cellspacing="0" border="0" role="presentation" style="border-collapse:collapse;">
            <tr>
              <td style="padding:0 0 9px 0;font-family:'Aptos','Segoe UI','Helvetica Neue',Arial,sans-serif;font-size:12.8px;line-height:1.35;font-weight:500;letter-spacing:0;color:#475569;">
                ${escapeHtml(data.signoff || 'Best regards,')}
              </td>
            </tr>
          </table>

          <table cellpadding="0" cellspacing="0" border="0" role="presentation" style="border-collapse:collapse;">
            <tr>
              <td style="padding:0 13px 0 0;vertical-align:top;">
                <img
                  src="${profileSrc}"
                  alt="${escapeHtml(data.profileAlt)}"
                  width="54"
                  height="54"
                  style="display:block;width:54px;height:54px;border-radius:999px;border:1px solid #d7dee8;background:#ffffff;object-fit:cover;object-position:center 12%;"
                />
              </td>
              <td style="padding:0;vertical-align:top;">
                <table cellpadding="0" cellspacing="0" border="0" role="presentation" style="border-collapse:collapse;">
                  <tr>
                    <td style="padding:0;font-family:'Aptos Display','Segoe UI','Helvetica Neue',Arial,sans-serif;font-size:24px;line-height:1.05;font-weight:700;letter-spacing:0;color:#0f172a;">
                      ${escapeHtml(data.name)}
                    </td>
                  </tr>
                  ${
                    hasAffiliation
                      ? `
                        <tr>
                          <td style="height:3px;font-size:1px;line-height:1px;">&nbsp;</td>
                        </tr>
                        ${affiliationRows
                          .map(
                            (row, index) => `
                              <tr>
                                <td style="padding:${index === 0 ? '0' : '1px 0 0 0'};font-family:'Aptos','Segoe UI','Helvetica Neue',Arial,sans-serif;font-size:12.8px;line-height:1.35;font-weight:${index === 0 ? '500' : '600'};letter-spacing:0;color:#334155;">
                                  ${escapeHtml(row)}
                                </td>
                              </tr>
                            `,
                          )
                          .join('')}
                      `
                      : ''
                  }
                </table>
              </td>
            </tr>
          </table>

          <table cellpadding="0" cellspacing="0" border="0" role="presentation" style="border-collapse:collapse;">
            <tr>
              <td style="height:9px;font-size:1px;line-height:1px;">&nbsp;</td>
            </tr>
          </table>

          <table cellpadding="0" cellspacing="0" border="0" role="presentation" style="border-collapse:collapse;">
            <tr>
              ${contactRailHtml}
            </tr>
          </table>

          <table cellpadding="0" cellspacing="0" border="0" role="presentation" style="border-collapse:collapse;">
            <tr>
              <td style="height:8px;font-size:1px;line-height:1px;">&nbsp;</td>
            </tr>
          </table>

          <table cellpadding="0" cellspacing="0" border="0" role="presentation" style="border-collapse:collapse;width:100%;">
            <tr>
              <td style="height:1px;background:#e5e7eb;font-size:1px;line-height:1px;">&nbsp;</td>
            </tr>
          </table>

          <table cellpadding="0" cellspacing="0" border="0" role="presentation" style="border-collapse:collapse;">
            <tr>
              <td style="height:9px;font-size:1px;line-height:1px;">&nbsp;</td>
            </tr>
          </table>

          ${logoRailHtml}
        </td>
      </tr>
    </table>
  `
}

export const buildSignatureHtml = (template: EmailSignatureTemplate) => {
  return `<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
  </head>
  <body style="margin:0;padding:0;background:#ffffff;">
    ${buildSignatureHtmlFragment(template)}
  </body>
</html>`
}
