import type { StudioEditSchema } from '@/types'

export const STUDIO_EDIT_SCHEMA: StudioEditSchema = {
  schemaVersion: '2026-03-30-ai-v2',
  assetOptions: {
    portraits: [
      { label: 'Profile (Default)', value: 'profile-tyler' },
      { label: 'Profile (Alt)', value: 'profile-tyler-alt' },
    ],
    signatures: [{ label: 'Tyler Signature', value: 'signature-tyler' }],
    logos: [
      { label: '73 Strings', value: '73strings' },
      { label: 'BMO', value: 'bmo' },
      { label: 'Bloomberg', value: 'bloomberg' },
      { label: 'CFA Institute', value: 'cfa' },
      { label: 'Coursera', value: 'coursera' },
      { label: 'CSI', value: 'csi' },
      { label: 'ETS', value: 'ets' },
      { label: 'ROI', value: 'roi' },
      { label: 'Grant Thornton', value: 'grant-thornton' },
      { label: 'Irving Oil', value: 'irving' },
      { label: 'McGill', value: 'mcgill' },
      { label: 'McGill Alt', value: 'mcgill-alt' },
      { label: "Queen's", value: 'queens' },
      { label: "Queen's Alt", value: 'queens-alt' },
      { label: 'RBC', value: 'rbc' },
      { label: 'Rotman', value: 'rotman' },
      { label: 'TD', value: 'td' },
      { label: 'Training The Street', value: 'training-the-street' },
      { label: 'UNB', value: 'unb' },
      { label: 'UNB Full', value: 'unb-full' },
      { label: 'United Way', value: 'united-way' },
      { label: 'UofT', value: 'uoft' },
      { label: 'Wall Street Prep', value: 'wall-street-prep' },
    ],
  },
  documents: {
    resume: {
      displayName: 'Resume',
      sections: [
        {
          id: 'header',
          label: 'Header',
          description: 'Update the portrait, title, summary, and compact contact rail.',
        },
        {
          id: 'contact-rail',
          label: 'Contact rail',
          description: 'Small metadata line shown under the identity block.',
        },
        {
          id: 'education',
          label: 'Education',
          description: 'White editorial entries matching the public resume system.',
        },
        {
          id: 'primary-experience',
          label: 'Primary experience',
          description: 'Top roles that lead the document.',
        },
        {
          id: 'additional-experience',
          label: 'Additional experience',
          description: 'Early-career and co-op groupings.',
        },
        {
          id: 'grouped-certifications',
          label: 'Grouped certifications',
          description: 'Public-resume style certification areas with editorial headings.',
        },
        {
          id: 'community',
          label: 'Community',
          description: 'Community entries now match the public resume structure.',
        },
      ],
      lockedRules: [
        'Headings such as Experience, Education, Certifications, and Community are system-owned.',
        'Section order, card structure, spacing, typography, margins, and PDF print rules are locked.',
        'Experience group layout, certification column placement, and community layout remain locked.',
      ],
      fieldTemplates: {
        header: [
          {
            key: 'name',
            fieldLabel: 'Name',
            valueType: 'string',
            allowedOps: ['replaceField'],
            affectsOutput: true,
          },
          {
            key: 'title',
            fieldLabel: 'Title',
            valueType: 'string',
            allowedOps: ['replaceField'],
            affectsOutput: false,
          },
          {
            key: 'profileSrc',
            fieldLabel: 'Portrait',
            valueType: 'asset',
            allowedOps: ['replaceField'],
            affectsOutput: true,
            assetSource: 'portraits',
          },
          {
            key: 'summary',
            fieldLabel: 'Summary',
            valueType: 'text',
            allowedOps: ['replaceField'],
            affectsOutput: true,
          },
        ],
        contactRail: [
          {
            key: 'email',
            fieldLabel: 'Email',
            valueType: 'string',
            allowedOps: ['replaceField'],
            affectsOutput: true,
          },
          {
            key: 'phone',
            fieldLabel: 'Phone',
            valueType: 'string',
            allowedOps: ['replaceField'],
            affectsOutput: true,
          },
          {
            key: 'website',
            fieldLabel: 'Website',
            valueType: 'string',
            allowedOps: ['replaceField'],
            affectsOutput: true,
          },
          {
            key: 'location',
            fieldLabel: 'Location',
            valueType: 'string',
            allowedOps: ['replaceField'],
            affectsOutput: true,
          },
        ],
        educationEntry: [
          {
            key: 'degree',
            fieldLabel: 'Degree',
            valueType: 'string',
            allowedOps: ['replaceField'],
            affectsOutput: true,
          },
          {
            key: 'program',
            fieldLabel: 'Program',
            valueType: 'string',
            allowedOps: ['replaceField'],
            affectsOutput: true,
          },
          {
            key: 'school',
            fieldLabel: 'School',
            valueType: 'string',
            allowedOps: ['replaceField'],
            affectsOutput: true,
          },
          {
            key: 'date',
            fieldLabel: 'Dates',
            valueType: 'date',
            allowedOps: ['replaceField'],
            affectsOutput: true,
          },
          {
            key: 'logoSrc',
            fieldLabel: 'Logo',
            valueType: 'asset',
            allowedOps: ['replaceField'],
            affectsOutput: true,
            assetSource: 'logos',
          },
          {
            key: 'bullets',
            fieldLabel: 'Highlights',
            valueType: 'stringList',
            allowedOps: ['replaceField', 'addListItem', 'removeListItem'],
            affectsOutput: true,
          },
        ],
        experienceGroup: [
          {
            key: 'title',
            fieldLabel: 'Group title',
            valueType: 'string',
            allowedOps: ['replaceField'],
            affectsOutput: false,
          },
          {
            key: 'layout',
            fieldLabel: 'Layout',
            valueType: 'metadata',
            allowedOps: [],
            affectsOutput: false,
          },
        ],
        experienceEntry: [
          {
            key: 'role',
            fieldLabel: 'Role',
            valueType: 'string',
            allowedOps: ['replaceField'],
            affectsOutput: true,
          },
          {
            key: 'company',
            fieldLabel: 'Company',
            valueType: 'string',
            allowedOps: ['replaceField'],
            affectsOutput: true,
          },
          {
            key: 'location',
            fieldLabel: 'Location',
            valueType: 'string',
            allowedOps: ['replaceField'],
            affectsOutput: true,
          },
          {
            key: 'date',
            fieldLabel: 'Dates',
            valueType: 'date',
            allowedOps: ['replaceField'],
            affectsOutput: true,
          },
          {
            key: 'logoSrc',
            fieldLabel: 'Logo',
            valueType: 'asset',
            allowedOps: ['replaceField'],
            affectsOutput: true,
            assetSource: 'logos',
          },
          {
            key: 'bullets',
            fieldLabel: 'Achievements',
            valueType: 'stringList',
            allowedOps: ['replaceField', 'addListItem', 'removeListItem'],
            affectsOutput: true,
          },
          {
            key: 'skills',
            fieldLabel: 'Skills',
            valueType: 'stringList',
            allowedOps: ['replaceField', 'addListItem', 'removeListItem'],
            affectsOutput: true,
          },
        ],
        certificationArea: [
          {
            key: 'title',
            fieldLabel: 'Area title',
            valueType: 'string',
            allowedOps: ['replaceField'],
            affectsOutput: true,
          },
          {
            key: 'column',
            fieldLabel: 'Column',
            valueType: 'metadata',
            allowedOps: [],
            affectsOutput: false,
          },
          {
            key: 'caption',
            fieldLabel: 'Caption',
            valueType: 'string',
            allowedOps: ['replaceField'],
            affectsOutput: true,
          },
          {
            key: 'summaryValue',
            fieldLabel: 'Summary value',
            valueType: 'string',
            allowedOps: ['replaceField'],
            affectsOutput: true,
          },
          {
            key: 'summaryLogos',
            fieldLabel: 'Summary logos',
            valueType: 'assetList',
            allowedOps: ['replaceField', 'addListItem', 'removeListItem'],
            affectsOutput: true,
            assetSource: 'logos',
          },
        ],
        certificationItem: [
          {
            key: 'name',
            fieldLabel: 'Name',
            valueType: 'string',
            allowedOps: ['replaceField'],
            affectsOutput: true,
          },
          {
            key: 'issuer',
            fieldLabel: 'Issuer',
            valueType: 'string',
            allowedOps: ['replaceField'],
            affectsOutput: true,
          },
          {
            key: 'year',
            fieldLabel: 'Year',
            valueType: 'date',
            allowedOps: ['replaceField'],
            affectsOutput: true,
          },
          {
            key: 'detail',
            fieldLabel: 'Detail',
            valueType: 'string',
            allowedOps: ['replaceField'],
            affectsOutput: true,
          },
          {
            key: 'logoSrc',
            fieldLabel: 'Logo',
            valueType: 'asset',
            allowedOps: ['replaceField'],
            affectsOutput: true,
            assetSource: 'logos',
          },
        ],
        leadershipGroup: [
          {
            key: 'title',
            fieldLabel: 'Group title',
            valueType: 'string',
            allowedOps: ['replaceField'],
            affectsOutput: false,
          },
          {
            key: 'layout',
            fieldLabel: 'Layout',
            valueType: 'metadata',
            allowedOps: [],
            affectsOutput: false,
          },
        ],
        leadershipItem: [
          {
            key: 'role',
            fieldLabel: 'Role',
            valueType: 'string',
            allowedOps: ['replaceField'],
            affectsOutput: true,
          },
          {
            key: 'organization',
            fieldLabel: 'Organization',
            valueType: 'string',
            allowedOps: ['replaceField'],
            affectsOutput: true,
          },
          {
            key: 'location',
            fieldLabel: 'Location',
            valueType: 'string',
            allowedOps: ['replaceField'],
            affectsOutput: true,
          },
          {
            key: 'date',
            fieldLabel: 'Dates',
            valueType: 'date',
            allowedOps: ['replaceField'],
            affectsOutput: true,
          },
          {
            key: 'logoSrc',
            fieldLabel: 'Logo',
            valueType: 'asset',
            allowedOps: ['replaceField'],
            affectsOutput: true,
            assetSource: 'logos',
          },
          {
            key: 'bullets',
            fieldLabel: 'Highlights',
            valueType: 'stringList',
            allowedOps: ['replaceField', 'addListItem', 'removeListItem'],
            affectsOutput: true,
          },
          {
            key: 'skills',
            fieldLabel: 'Skills',
            valueType: 'stringList',
            allowedOps: ['replaceField', 'addListItem', 'removeListItem'],
            affectsOutput: true,
          },
        ],
      },
      collectionTemplates: [
        {
          id: 'data.education',
          sectionId: 'education',
          sectionLabel: 'Education',
          entryType: 'educationEntry',
          allowedOps: ['createEntry', 'deleteEntry'],
        },
        {
          id: 'data.experience.primary',
          sectionId: 'primary-experience',
          sectionLabel: 'Primary experience',
          entryType: 'experienceEntry',
          allowedOps: ['createEntry', 'deleteEntry'],
        },
        {
          id: 'data.experience.groups',
          sectionId: 'additional-experience',
          sectionLabel: 'Additional experience',
          entryType: 'experienceGroup',
          allowedOps: [],
        },
        {
          id: 'data.certifications.areas',
          sectionId: 'grouped-certifications',
          sectionLabel: 'Grouped certifications',
          entryType: 'certificationArea',
          allowedOps: ['createEntry', 'deleteEntry'],
        },
        {
          id: 'data.leadership',
          sectionId: 'community',
          sectionLabel: 'Community',
          entryType: 'leadershipGroup',
          allowedOps: [],
        },
      ],
    },
    'cover-letter': {
      displayName: 'Cover letter',
      sections: [
        {
          id: 'template',
          label: 'Template',
          description: 'Presets change sender defaults and context, not the visual system.',
        },
        {
          id: 'sender',
          label: 'Sender',
          description: 'Contact details shown in the editorial header and signoff.',
        },
        {
          id: 'recipient',
          label: 'Recipient',
          description: 'Opportunity context and addressee details.',
        },
        {
          id: 'body',
          label: 'Body',
          description: 'Editorial letter body with readable spacing and print output.',
        },
      ],
      lockedRules: [
        'The shared identity summary line, print margins, spacing, and typography are locked.',
        'The editorial document structure and signoff layout remain system-owned.',
      ],
      fieldTemplates: {
        template: [
          {
            key: 'presetLabel',
            fieldLabel: 'Preset label',
            valueType: 'string',
            allowedOps: ['replaceField'],
            affectsOutput: false,
          },
          {
            key: 'tagline',
            fieldLabel: 'Tagline',
            valueType: 'string',
            allowedOps: ['replaceField'],
            affectsOutput: false,
          },
          {
            key: 'contextNote',
            fieldLabel: 'Context note',
            valueType: 'string',
            allowedOps: ['replaceField'],
            affectsOutput: false,
          },
          {
            key: 'profileSrc',
            fieldLabel: 'Portrait',
            valueType: 'asset',
            allowedOps: ['replaceField'],
            affectsOutput: true,
            assetSource: 'portraits',
          },
          {
            key: 'signatureSrc',
            fieldLabel: 'Signature',
            valueType: 'asset',
            allowedOps: ['replaceField'],
            affectsOutput: true,
            assetSource: 'signatures',
          },
        ],
        sender: [
          {
            key: 'yourName',
            fieldLabel: 'Your name',
            valueType: 'string',
            allowedOps: ['replaceField'],
            affectsOutput: true,
          },
          {
            key: 'yourEmail',
            fieldLabel: 'Email',
            valueType: 'string',
            allowedOps: ['replaceField'],
            affectsOutput: true,
          },
          {
            key: 'yourPhone',
            fieldLabel: 'Phone',
            valueType: 'string',
            allowedOps: ['replaceField'],
            affectsOutput: true,
          },
          {
            key: 'yourWebsite',
            fieldLabel: 'Website',
            valueType: 'string',
            allowedOps: ['replaceField'],
            affectsOutput: true,
          },
          {
            key: 'yourAddress',
            fieldLabel: 'Location',
            valueType: 'string',
            allowedOps: ['replaceField'],
            affectsOutput: true,
          },
        ],
        recipient: [
          {
            key: 'companyName',
            fieldLabel: 'Company',
            valueType: 'string',
            allowedOps: ['replaceField'],
            affectsOutput: true,
          },
          {
            key: 'position',
            fieldLabel: 'Position',
            valueType: 'string',
            allowedOps: ['replaceField'],
            affectsOutput: true,
          },
          {
            key: 'hiringManager',
            fieldLabel: 'Hiring manager',
            valueType: 'string',
            allowedOps: ['replaceField'],
            affectsOutput: true,
          },
          {
            key: 'date',
            fieldLabel: 'Date',
            valueType: 'date',
            allowedOps: ['replaceField'],
            affectsOutput: true,
          },
          {
            key: 'companyAddress',
            fieldLabel: 'Company address',
            valueType: 'text',
            allowedOps: ['replaceField'],
            affectsOutput: true,
          },
        ],
        body: [
          {
            key: 'openingParagraph',
            fieldLabel: 'Opening',
            valueType: 'text',
            allowedOps: ['replaceField'],
            affectsOutput: true,
          },
          {
            key: 'bodyParagraph1',
            fieldLabel: 'Body paragraph 1',
            valueType: 'text',
            allowedOps: ['replaceField'],
            affectsOutput: true,
          },
          {
            key: 'bodyParagraph2',
            fieldLabel: 'Body paragraph 2',
            valueType: 'text',
            allowedOps: ['replaceField'],
            affectsOutput: true,
          },
          {
            key: 'bodyParagraph3',
            fieldLabel: 'Body paragraph 3',
            valueType: 'text',
            allowedOps: ['replaceField'],
            affectsOutput: true,
          },
          {
            key: 'closingParagraph',
            fieldLabel: 'Closing',
            valueType: 'text',
            allowedOps: ['replaceField'],
            affectsOutput: true,
          },
        ],
      },
      collectionTemplates: [],
    },
    'email-signature': {
      displayName: 'Email signature',
      sections: [
        {
          id: 'template',
          label: 'Template',
          description: 'Unified signature styling with content presets only.',
        },
        {
          id: 'identity',
          label: 'Identity',
          description: 'Preview and export share the same updated structure.',
        },
        {
          id: 'html',
          label: 'HTML',
          description: 'Copy or download the production-ready signature HTML.',
        },
      ],
      lockedRules: [
        'The contact rail order, icon order, muted logo treatment, and typography are locked.',
        'HTML table structure and email-safe formatting remain system-owned.',
        'Experience logos and education logos are edited separately and stay grouped in the final signature.',
      ],
      fieldTemplates: {
        identity: [
          {
            key: 'name',
            fieldLabel: 'Name',
            valueType: 'string',
            allowedOps: ['replaceField'],
            affectsOutput: true,
          },
          {
            key: 'role',
            fieldLabel: 'Role',
            valueType: 'string',
            allowedOps: ['replaceField'],
            affectsOutput: true,
          },
          {
            key: 'organization',
            fieldLabel: 'Organization',
            valueType: 'string',
            allowedOps: ['replaceField'],
            affectsOutput: true,
          },
          {
            key: 'signoff',
            fieldLabel: 'Signoff',
            valueType: 'string',
            allowedOps: ['replaceField'],
            affectsOutput: true,
          },
          {
            key: 'email',
            fieldLabel: 'Email',
            valueType: 'string',
            allowedOps: ['replaceField'],
            affectsOutput: true,
          },
          {
            key: 'website',
            fieldLabel: 'Website',
            valueType: 'string',
            allowedOps: ['replaceField'],
            affectsOutput: true,
          },
          {
            key: 'phone',
            fieldLabel: 'Phone',
            valueType: 'string',
            allowedOps: ['replaceField'],
            affectsOutput: true,
          },
          {
            key: 'location',
            fieldLabel: 'Location',
            valueType: 'string',
            allowedOps: ['replaceField'],
            affectsOutput: true,
          },
          {
            key: 'profileSrc',
            fieldLabel: 'Portrait',
            valueType: 'asset',
            allowedOps: ['replaceField'],
            affectsOutput: true,
            assetSource: 'portraits',
          },
          {
            key: 'experienceLogos',
            fieldLabel: 'Experience logos',
            valueType: 'assetList',
            allowedOps: ['replaceField', 'addListItem', 'removeListItem'],
            affectsOutput: true,
            assetSource: 'logos',
          },
          {
            key: 'educationLogos',
            fieldLabel: 'Education logos',
            valueType: 'assetList',
            allowedOps: ['replaceField', 'addListItem', 'removeListItem'],
            affectsOutput: true,
            assetSource: 'logos',
          },
          {
            key: 'logoTone',
            fieldLabel: 'Logo tone',
            valueType: 'metadata',
            allowedOps: [],
            affectsOutput: false,
          },
        ],
      },
      collectionTemplates: [],
    },
  },
}

export const STUDIO_ASSET_OPTIONS = STUDIO_EDIT_SCHEMA.assetOptions
